blank_issues_enabled: false
contact_links:
  - name: Juan SebastiÃ¡n DÃ­az Osorio
    url: https://github.com/juansedo
    about: Please ask and answer questions here. ğŸ¥
  - name: David Calle GonzÃ¡lez
    url: https://github.com/dcalleg707
    about: Please ask and answer questions here. ğŸ¥
  - name: Santiago Hidalgo Ocampo
    url: https://github.com/sanhidalgoo
    about: Please ask and answer questions here. ğŸ¥
